# Generated by Django 5.2 on 2025-05-05 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechahoraPedido', models.DateTimeField(auto_now_add=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_mesa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=100)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('rol', models.CharField(choices=[('ADM', 'Administrador'), ('MES', 'Mesero')], default='ADM', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=45)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Pedidos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.pedidos')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=45)),
                ('Cantidad', models.CharField(max_length=50)),
                ('precioProducto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('cantidadPersonas', models.IntegerField()),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='pedidos',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.usuario'),
        ),
    ]
