# Generated by Django 5.1.1 on 2025-05-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alter_pedido_mesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(related_name='pedidos', to='inicio.producto'),
        ),
    ]
