# Generated by Django 5.2 on 2025-05-06 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_factura_reserva'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Factura',
        ),
    ]
