# Generated by Django 5.2 on 2025-05-10 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_categoria_rol_remove_pedidos_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BebidaCaliente',
            fields=[
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inicio.producto')),
                ('tipo', models.CharField(choices=[('CAFE', 'Café'), ('TE', 'Té'), ('CHOCOLATE', 'Chocolate caliente'), ('INFUSION', 'Infusión')], default='CAFE', max_length=50)),
            ],
        ),
    ]
