# Generated by Django 5.2 on 2025-05-11 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_bebidacaliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BebidaCaliente',
        ),
    ]
