# Generated by Django 5.2 on 2025-05-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_delete_bebidacaliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='nombreProducto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.AddField(
            model_name='producto',
            name='available',
            field=models.BooleanField(default=True, verbose_name='disponible'),
        ),
        migrations.AddField(
            model_name='producto',
            name='description',
            field=models.TextField(default='Sin descripción', verbose_name='descripcion'),
        ),
        migrations.AddField(
            model_name='producto',
            name='name',
            field=models.CharField(default='Producto sin nombre', max_length=200, verbose_name='nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='foto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=10, verbose_name='precio'),
            preserve_default=False,
        ),
    ]
