# Generated by Django 5.2 on 2025-06-12 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0027_merge_20250601_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio.producto'),
        ),
    ]
