# Generated by Django 5.2 on 2025-06-12 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0029_pedidodetalle_nombre_producto_historico_and_more'),
    ]

    operations = [
    ]
