# Generated by Django 5.2 on 2025-06-12 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0029_alter_producto_titulo'),
        ('inicio', '0030_auto_20250611_2003'),
    ]

    operations = [
    ]
