# Generated by Django 5.2 on 2025-06-12 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0031_merge_20250612_1618'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pedidodetalle',
            unique_together=set(),
        ),
    ]
